# Generated by Django 4.0.2 on 2022-07-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='user',
            field=models.CharField(default='Anonymous', max_length=10000),
        ),
    ]
